[package]
name = "render"
version = "0.1.0"
authors = ["Rishabh Bector <bector.rishabh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.10"
cgmath = "0.17.0"
